import Head from 'next/head'
import Aside from '../components/Aside'
import Main from '../components/Main'
import styles from '../styles/Action.module.scss'

export default function action({games}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Action Games</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <section className={styles["layout"]}>
        <main className={styles['main']}>
          <Aside />
          <Main games={games}/>
        </main>
        
      </section>
    </div>
  )
}

// call the api to get featured games
export async function getStaticProps() {

  const apiRoot= 'https://rawg.io/api/games'

  const res = await fetch(`${apiRoot}?${process.env.rawgkey}&genres=4&metacritic=80,100&dates=2021-01-01,2022-06-01&ordering=-metacritic`)

  const gameData = await res.json()

  return {
    props: {games: gameData},
  }
}