import Head from 'next/head'
import Main from '../components/Main'
import styles from '../styles/Action.module.scss'

export default function action({games}) {

  const pageName = 'NEW RELEASES'

  return (
    <div className={styles.container}>
      <Head>
        <title>New Releases</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <section className={styles["layout"]}>
        <main className={styles['main']}>
          <Main games={games} pageName={pageName}/>
        </main>
        
      </section>
    </div>
  )
}

// call the api to get featured games
export async function getStaticProps() {

  const apiRoot= 'https://rawg.io/api/games'

  // fetch top release
  const topRelRes = await fetch(`${apiRoot}?${process.env.rawgkey}&dates=2022-02-08,2022-03-08&ordering=-metacritic&page=1&page_size=20`)

  const topRel = await topRelRes.json()

  return {
    props: {games: topRel},
  }
}