import Head from 'next/head'
import Main from '../components/Main'
import styles from '../styles/Action.module.scss'

export default function action({games}) {

  const pageName = 'NEW RELEASES'

  return (
    <div className={styles.container}>
      <Head>
        <title>New Releases</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <section className={styles["layout"]}>
        <main className={styles['main']}>
          <Main games={games} pageName={pageName}/>
        </main>
        
      </section>
    </div>
  )
}

// call the api to get featured games
export async function getStaticProps() {

  const apiRoot= 'https://rawg.io/api/games'

  // handle the dates
  var date = new Date()
  var day = ("0" + (date.getDate())).slice(-2)
  var month = ("0" + (date.getMonth() + 1)).slice(-2)
  var year = date.getFullYear()

  // set last month
  date.setDate(date.getDate() - 30);
  var lastMonth = ("0" + (date.getMonth() + 1)).slice(-2)

  // fetch top release
  const topRelRes = await fetch(`${apiRoot}?${process.env.rawgkey}&dates=${year}-${lastMonth}-${day},${year}-${month}-${day}&ordering=-metacritic&page=1&page_size=20`)

  const topRel = await topRelRes.json()

  return {
    props: {games: topRel},
  }
}