import Head from 'next/head'
import React, { Fragment } from 'react'
import styles from '../styles/components/_article.module.scss'

function reviews({reviews}) {

  const reviewsCard = reviews.results.map((a, i) => {
    return (
      <Fragment key={i}>
        <div className={styles['article_card']}>
          <a href={a.site_detail_url} target={"_blank"} rel={"noreferrer"} className={styles['article_card-img']}>
            <img src={a.image.original}></img> 
            <div className={styles['article_card-summary']}><p>{a.deck}</p></div>
          </a>
          {/* get string before space */}
          <p>{a.publish_date.split(' ')[0]}</p>
          <div>{a.title}</div>
        </div>
      </Fragment>
    )
  })
  return (
    <Fragment>

      <Head>
        <title>Reviews</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles['main']}>
        <div>
          <h1 className={styles['page-title']}>REVIEWS</h1>
          <h2 className={styles['page-subtitle']}>Recent Reviews from Game Spot</h2>
          <article className={styles['main-layout']}>
            {reviewsCard}
          </article>

        </div>

      </main>
    </Fragment>
  )
}

export default reviews

// call the api to get featured games
export async function getStaticProps() {

  const res = await fetch(`https://www.gamespot.com/api/reviews/?api_key=eea4c300a10d9eda7d70b3d903f0cf1266f3d73b&format=json&limit=12&sort=publish_date:desc`)

  
  const articleData = await res.json()
  
  return {
    props: {reviews: articleData},
  }
}