import Head from 'next/head'
import Main from '../components/Main'
import styles from '../styles/Action.module.scss'
import React from 'react'

export default function action({games}) {

  const pageName = 'UP COMING'

  return (
    <div className={styles.container}>
      <Head>
        <title>Up Coming Games</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <section className={styles["layout"]}>
        
        {/* <div style={{marginLeft: '70px'}}>
          <h1>UP COMING</h1>
        </div> */}

        <main className={styles['main']}>
          <Main games={games} pageName={pageName}/>
        </main>
        
      </section>
    </div>
  )
}

// call the api to get featured games
export async function getStaticProps() {

  const apiRoot= 'https://rawg.io/api/games'

  // handle the dates
  var date = new Date()
  var day = ("0" + (date.getDate())).slice(-2)
  var month = ("0" + (date.getMonth() + 1)).slice(-2)
  var year = date.getFullYear()

  // set future dates
  date.setDate(date.getDate() + 180);
  var nextHalf = ("0" + (date.getMonth() + 1)).slice(-2)
  var nextYear = date.getFullYear()

  // fetch upcoming
  const upcomingGames = await fetch(`${apiRoot}?${process.env.rawgkey}&dates=${year}-${month}-${day},${nextYear}-${nextHalf}-${day}&ordering=-rating&page=1&page_size=15`)

  const upcoming = await upcomingGames.json()

  return {
    props: {
      games: upcoming,
    },
  }
}