import Head from 'next/head'
import Main from '../components/Main'
import styles from '../styles/Action.module.scss'

export default function action({games}) {

  const pageName = 'UP COMING'

  return (
    <div className={styles.container}>
      <Head>
        <title>Action Games</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <section className={styles["layout"]}>
        
        {/* <div style={{marginLeft: '70px'}}>
          <h1>UP COMING</h1>
        </div> */}

        <main className={styles['main']}>
          <Main games={games} pageName={pageName}/>
        </main>
        
      </section>
    </div>
  )
}

// call the api to get featured games
export async function getStaticProps() {

  const apiRoot= 'https://rawg.io/api/games'

  // fetch upcoming
  const upcomingGames = await fetch(`${apiRoot}?${process.env.rawgkey}&dates=2022-03-08,2022-09-08&ordering=-rating&page=1&page_size=15`)

  const upcoming = await upcomingGames.json()

  return {
    props: {games: upcoming},
  }
}